### ISSUE TITLE
self.entity_eir not defined in calculate_vals

### ISSUE THREAD

**Issue by leonhardrocha** [jamescalam/finance_models#1]
self.entity_eir not defined in calculate_vals function and I have no ideia what it is to fix it.

**Comment by jamescalam** [comment]
@leonhardrocha we use this when we are comparing our calculated EIR against a client/entity calculated EIR, during simplification of the code it seems this was not integrated correctly, I have added checks for this in the initialisation of Cashflow and the calculate_vals method. Has this solved your issue?

**Comment by leonhardrocha** [comment]
Hi James,

First I would like to thank you for your collaboration posting your
project. What lack me most is accounting background, so I have to
understand the formulae, not the name of the column...

I trying to reproduce and understand it, and maybe, improve it to
convert it to full pandas operations, which would turn it more
readable. Although numpy is faster than pandas, it can be used under
the hood. I have corverted around 50% of the code, fixing import
issues, as correct typing of columns, etc. I totally understand that
your code is a port from another project, I often do the same
mistakes.

I appreciate you reply and hope we can improve the cashflow_eir module together.

Regards,

Leonardo

Ps. I make to module fully executable, but I had to comment a few
lines, so I could output to csv file without some missing columns.
I'll fork the github and submit the changes later today.

**Comment by jamescalam** [comment]
@leonhardrocha no problem, happy to help.

If you're able to improve readability without reducing performance then yes please do, more than happy for you to improve the module!

Let me know if you have anymore questions, or suggestions, feel free to submit any improvements.

Thanks!
